/**
 * Turns `dist/` into something SiteGround can serve: `npm run build:siteground`.
 *
 * SiteGround's shared hosting runs PHP, not Node, so the api/*.js handlers do
 * not run there. server/public/ holds their PHP ports and the .htaccess that
 * mounts them at the same /api/<name> URLs; this copies them over the build.
 *
 * It also exports what HatBot knows — the system prompt and tools from
 * api/knowledge.js, the built-in answers from api/fallback.js — into
 * dist/api/_knowledge.php. Those two JS files stay the single source: the PHP
 * reads the export and never has a copy of its own to drift. A .php file rather
 * than .json on purpose: requested over HTTP it executes and prints nothing, so
 * even if the .htaccess block on `_` files were lost, the prompt would not be
 * served.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { PATHS, SYSTEM_PROMPT, TOOLS } from '../api/knowledge.js'
import { OFFER_MARKER, OPENED_REPLY, TOPICS, UNKNOWN_REPLY, YES } from '../api/fallback.js'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const dist = path.join(root, 'dist')
const serverPublic = path.join(root, 'server', 'public')

if (!fs.existsSync(path.join(dist, 'index.html'))) {
  console.error('[stage-php] dist/index.html is missing — run `npm run build` first.')
  process.exit(1)
}

fs.cpSync(serverPublic, dist, { recursive: true })

/**
 * `--staging` tells search engines to stay away: a staging copy that gets
 * indexed competes with the real site for its own name. A response header, not
 * robots.txt — a Disallow stops the crawler reading the page, so it never sees
 * a noindex and can still list the URL from links to it.
 *
 * Opt-in, not opt-out, on purpose. Forgetting the flag on staging costs a
 * duplicate that the canonical tag already points back to the real domain;
 * forgetting to remove it at launch would quietly de-list the real site.
 */
if (process.argv.includes('--staging')) {
  fs.appendFileSync(
    path.join(dist, '.htaccess'),
    '\n# Staging build (--staging): keep this copy out of search results.\n' +
      '<IfModule mod_headers.c>\n  Header always set X-Robots-Tag "noindex, nofollow"\n</IfModule>\n',
  )
  console.log('[stage-php] staging build: every response carries X-Robots-Tag: noindex')
}

const knowledge = {
  systemPrompt: SYSTEM_PROMPT,
  tools: TOOLS,
  paths: PATHS,
  fallback: {
    topics: TOPICS.map(({ match, ...topic }) => ({ ...topic, match: match.source })),
    yes: YES.source,
    offerMarker: OFFER_MARKER,
    openedReply: OPENED_REPLY,
    unknownReply: UNKNOWN_REPLY,
  },
}

const json = JSON.stringify(knowledge, null, 1)
// A nowdoc ends at the first line that is exactly its label.
if (/^KNOWLEDGE;?$/m.test(json)) throw new Error('knowledge contains the nowdoc terminator')

const php = `<?php
// Generated by scripts/stage-php.mjs from api/knowledge.js and api/fallback.js.
// Do not edit — edit those, then rebuild.
return json_decode(<<<'KNOWLEDGE'
${json}
KNOWLEDGE, true, 512, JSON_THROW_ON_ERROR);
`
fs.writeFileSync(path.join(dist, 'api', '_knowledge.php'), php)

const copied = fs.readdirSync(path.join(dist, 'api')).join(', ')
console.log(`[stage-php] dist/ is ready for SiteGround (api/: ${copied})`)
